CREATE TABLE client
(
    client_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name      VARCHAR(200) NOT NULL CHECK ( length(name) >= 3 )
);

CREATE TABLE planet
(
    planet_id VARCHAR PRIMARY KEY,
    name VARCHAR(500) NOT NULL,
    CONSTRAINT valid_id CHECK ( planet_id ~ '^[A-Z0-9]+$' )
);

CREATE TABLE ticket
(
    ticket_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    create_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    client_id INT REFERENCES client(client_id) ON DELETE CASCADE,
    from_planet_id VARCHAR REFERENCES planet(planet_id) ON DELETE CASCADE,
    to_planet_id VARCHAR REFERENCES planet(planet_id) ON DELETE CASCADE
);